services:
  node20:
    image: mcr.microsoft.com/devcontainers/javascript-node:20
    container_name: devcontainer-node20
    volumes:
      - ${PROJECT_DIR:-/tmp}:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
    network_mode: bridge

  node22:
    image: mcr.microsoft.com/devcontainers/javascript-node:22
    container_name: devcontainer-node22
    volumes:
      - ${PROJECT_DIR:-/tmp}:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
    network_mode: bridge

  node24:
    image: mcr.microsoft.com/devcontainers/javascript-node:24
    container_name: devcontainer-node24
    volumes:
      - ${PROJECT_DIR:-/tmp}:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
    network_mode: bridge
